/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import java.io.File


fun printBoard(grid: IntArray) {
    for (i in 0..8) {
        for (j in 0..8) {
            print("${grid[i * 9 + j]} ")
            if (j == 2 || j == 5) print("| ")
        }
        println()
        if (i == 2 || i == 5) println("------+-------+------")
    }
}

fun main(args: Array<String>) {
    if (args.isEmpty()) {
        println("Error: Please provide a filename as a command line argument.")
        return
    }

    val fileName = args[0]
    val rows = File(fileName).readLines()

    println("Input board:\n")
    val sudoku = Sudoku(rows)
    printBoard(sudoku.getGrid())

    println("\nSolving...\n")

    if (sudoku.solve()) {
        println("Solution:\n")
        printBoard(sudoku.getGrid())
    } else {
        println("Could not find a solution.")
    }
}

